# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  param_fetcher_listener:  true
  allowed_methods_listener:  true
  disable_csrf_role: ROLE_ADMIN
  view:
    view_response_listener:  'force'
    mime_types:
      json: [ 'application/json; charset=UTF-8', 'application/json' ]

  format_listener:
      rules:
        - { path: '^/it/api/', priorities: [ 'json' ], fallback_format: json, prefer_extension: true }
        - { path: '^/', priorities: [ 'html', '*/*' ], fallback_format: html, prefer_extension: true }
