framework:
    #default_locale: '%locale%'
    default_locale: 'it'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            #- '%locale%'
            - 'it'
